
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway
  lifecycle:
    timeout-per-shutdown-phase: 20s

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: hotel-service
              uri: lb://hotel-service
              predicates:
                - Path=/hotels/**

            - id: rating-service
              uri: lb://rating-service
              predicates:
                - Path=/ratings/**

          discovery:
            locator:
              enabled: false

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                  - HEAD
                allowedHeaders: "*"
                exposedHeaders:
                  - Location
                allowCredentials: false
                maxAge: 3600

logging:
  level:
    com.apigateway: INFO
    org.springframework.cloud.gateway: INFO
