server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: hotel-service
  lifecycle:
    timeout-per-shutdown-phase: 20s

  datasource:
    url: jdbc:postgresql://ep-noisy-boat-b5hysx4q-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_uQeByA2ghr0d
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HotelServiceHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      keepalive-time: 120000
      validation-timeout: 5000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false

logging:
  level:
    com.hotelservice: INFO
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: INFO
